config/routes.rb
PivotalReporter::Engine.routes.draw do

  resources :stories do
    member do
      get 'accept' => 'stories#accept', to: :accept_story
      get 'reject' => 'stories#reject', to: :reject_story
    end
  end

  root :to => 'stories#new'

end

app/controllers/pivotal_reporter/application_controller.rb
module PivotalReporter
  class ApplicationController < ActionController::Base

    PivotalTracker::Client.token = PivotalReporter::Engine.config.token

    def pivotal_project
      PivotalTracker::Project.find(PivotalReporter::Engine.config.project_id)
    end

    def pivotal_unique_label
      "pivotal_reporter_#{PivotalReporter::Engine.config.project_id}"
    end

  end

end

app/controllers/pivotal_reporter/stories_controller.rb
require_dependency "pivotal_reporter/application_controller"

module PivotalReporter
  class StoriesController < ApplicationController
    def index
      @stories = pivotal_project.stories.all(label: pivotal_unique_label)
    end

    def show
      @story = pivotal_project.stories.find(params[:id])
    end

    def new
      @pivotal_unique_label = pivotal_unique_label
    end
  
    def create
      story = PivotalTracker::Story.new(params[:story]).create

      if story.errors.count > 0
        flash[:error] = "Report Submission Failed: #{story.errors}"
      else
        flash[:success] = 'Report Submitted!'
      end

      redirect_to new_story_path
    end

    def accept
      @story = pivotal_project.stories.find(params[:id])
      @story.update({current_state: 'accepted'})

      redirect_to stories_path
    end

    def reject
      @story = pivotal_project.stories.find(params[:id])
      @story.update({current_state: 'rejected'})
      @story.notes.create(:text => URI.decode(params[:reject_message]))

      redirect_to stories_path
    end


  end
end

app/controllers/public_tracker/stories_controller.rb
require_dependency "public_tracker/application_controller"

module PublicTracker
  class StoriesController < ApplicationController
    def index
      @stories = pivotal_project.stories.all(label: pivotal_unique_label)
    end

    def show
      @story = pivotal_project.stories.find(params[:id])
    end

    def new
      @pivotal_unique_label = pivotal_unique_label
    end
  
    def create
      story = PivotalTracker::Story.new(params[:story]).create

      if story.errors.count > 0
        flash[:error] = "Report Submission Failed: #{story.errors}"
      else
        flash[:success] = 'Report Submitted!'
        #redirect_to stories_path
      end
      redirect_to new_story_path
    end
  end
end

app/helpers/pivotal_reporter/application_helper.rb
module PivotalReporter
  module ApplicationHelper

    def pivotal_labels
      "#{@pivotal_unique_label}, remote_user_#{requested_by.gsub(' ', '').underscore}"
    end

    def requested_by
      PivotalReporter::Engine.config.request_user || current_user.full_name
    end


  end
end

app/helpers/pivotal_reporter/stories_helper.rb
module PivotalReporter
  module StoriesHelper
  end
end

app/views/layouts/pivotal_reporter/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PivotalReporter</title>
  <%= stylesheet_link_tag    "pivotal_reporter/application", :media => "all" %>
  <%= javascript_include_tag "pivotal_reporter/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pivotal_reporter/stories/index.html.erb
<%= link_to "Submit New Report", new_story_path  %>
<table>
  <thead>
  <tr>
    <th class="type">Type</th>
    <th class="status">Status</th>
    <th>Description</th>
  </tr>
  </thead>
  <tbody>
  <% @stories.each do |story| %>
    <tr>
      <td class="type"><a href="<%= story.url %>" class="<%= story.story_type %>" title="<%= story.story_type %> <%= story.id %>"><%= story.story_type[0].capitalize %></a></td>
      <td class="status">
        <%= story.current_state.capitalize %>
        <% if story.current_state == 'delivered' %>
            <%= link_to 'Accept', accept_story_path(story.id), class: 'accept-btn' %>
            <%= link_to 'Reject', '#', class: 'reject-btn', :'data-reject-path' => reject_story_path(story.id) %>
        <% end %>
      </td>
      <td><%= story.name %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "Submit New Report", new_story_path  %>

app/views/pivotal_reporter/stories/new.html.erb
<% if flash[:success] %>
    <div class="success"><%= flash[:success] %></div>
<% end %>

<form method="post" action="<%= PivotalReporter::Engine.config.mount_point %>/stories">
    <label for="story[story_type]">Type</label>
    <select name="story[story_type]">
      <option value="bug">Bug</option>
      <option value="feature">Feature</option>
    </select>
    <br />

    <label for="story[name]">Title</label>
    <input type="text" name="story[name]" />
    <br />

    <label for="story[description]">Description</label>
    <textarea name="story[description]"></textarea>
    <br />

    <input type="hidden" name="story[labels]" value="<%= pivotal_labels %>" />
    <input type="hidden" name="story[project_id]" value="<%= PivotalReporter::Engine.config.project_id %>" />
    <input type="hidden" name="story[requested_by]" value="<%= requested_by %>" />

    <input type="submit" value="Report" />

</form>

<%= link_to "View Your Active Submissions", stories_path %>